server:
    port: 8087
spring:
    cloud:
        stream:
            bindings:
                incoming-out-0:
                    destination: tweets
            kafka:
                binder:
                    brokers:
                        - localhost:9092


